name: Java CI with Maven

on: [push, pull_request]  # Runs on push and pull request events

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use Eclipse Temurin JDK
          java-version: '19'
          cache: maven  # Caches Maven dependencies for faster builds

      - name: Build with Maven
        run: mvn clean install --batch-mode --fail-at-end

      - name: Run Tests
        run: mvn test --batch-mode

